import React, { useContext } from 'react';
import { CVData } from '../types';
import { LanguageContext } from '../App';

interface CVPreviewProps {
    cvData: CVData;
    onEdit: () => void;
    onExport: () => void;
    onOpenAssistant: () => void;
}

const CVPreview: React.FC<CVPreviewProps> = ({ cvData, onEdit, onExport, onOpenAssistant }) => {
    const { t } = useContext(LanguageContext);

    return (
        <div className="w-full max-w-4xl mx-auto bg-white p-8 rounded-xl shadow-lg border border-gray-200">
            <div className="flex justify-between items-center mb-6 border-b pb-4">
                <h2 className="text-3xl font-bold text-gray-800">Preview</h2>
                <div className="flex gap-2">
                    <button onClick={onEdit} className="bg-gray-200 text-gray-800 font-bold py-2 px-4 rounded-lg hover:bg-gray-300 transition-colors">Edit</button>
                    <button onClick={onOpenAssistant} className="bg-purple-600 text-white font-bold py-2 px-4 rounded-lg hover:bg-purple-700 transition-colors">{t('applicationAssistant')}</button>
                    <button onClick={onExport} className="bg-indigo-600 text-white font-bold py-2 px-4 rounded-lg hover:bg-indigo-700 transition-colors">Export</button>
                </div>
            </div>

            {/* This is a simple preview. The actual design is generated by Gemini in the ExportModal. */}
            <div className="space-y-6">
                <div className="flex items-center gap-6">
                    {cvData.personalInfo.profilePhoto && (
                        <img src={cvData.personalInfo.profilePhoto} alt="Profile" className="w-32 h-32 rounded-full object-cover" />
                    )}
                    <div>
                        <h1 className="text-4xl font-bold">{cvData.personalInfo.name}</h1>
                        <div className="text-gray-600 mt-2 space-y-1">
                            <p>{cvData.personalInfo.email}</p>
                            <p>{cvData.personalInfo.phone}</p>
                            <p>{cvData.personalInfo.address}</p>
                            {cvData.personalInfo.linkedin && <p>LinkedIn: <a href={cvData.personalInfo.linkedin} className="text-blue-600">{cvData.personalInfo.linkedin}</a></p>}
                            {cvData.personalInfo.website && <p>Website: <a href={cvData.personalInfo.website} className="text-blue-600">{cvData.personalInfo.website}</a></p>}
                        </div>
                    </div>
                </div>

                <div>
                    <h3 className="text-2xl font-semibold border-b-2 border-gray-300 pb-1 mb-2">{t('professionalSummary')}</h3>
                    <p className="text-gray-700 whitespace-pre-wrap">{cvData.summary}</p>
                </div>

                <div>
                    <h3 className="text-2xl font-semibold border-b-2 border-gray-300 pb-1 mb-2">{t('workExperience')}</h3>
                    {cvData.experience.map(exp => (
                        <div key={exp.id} className="mb-4">
                            <h4 className="text-xl font-bold">{exp.jobTitle}</h4>
                            <p className="font-semibold text-gray-800">{exp.company} | {exp.location}</p>
                            <p className="text-sm text-gray-500">{exp.startDate} - {exp.endDate}</p>
                            <p className="text-gray-700 mt-1 whitespace-pre-wrap">{exp.description}</p>
                        </div>
                    ))}
                </div>

                <div>
                    <h3 className="text-2xl font-semibold border-b-2 border-gray-300 pb-1 mb-2">{t('education')}</h3>
                    {cvData.education.map(edu => (
                        <div key={edu.id} className="mb-4">
                            <h4 className="text-xl font-bold">{edu.degree}</h4>
                            <p className="font-semibold text-gray-800">{edu.school} | {edu.location}</p>
                            <p className="text-sm text-gray-500">{edu.gradDate}</p>
                        </div>
                    ))}
                </div>

                 <div>
                    <h3 className="text-2xl font-semibold border-b-2 border-gray-300 pb-1 mb-2">{t('skills')}</h3>
                    <p className="text-gray-700">{cvData.skills.join(', ')}</p>
                </div>
            </div>
        </div>
    );
};

export default CVPreview;
