import { GoogleGenAI, Type, Modality } from "@google/genai";
import type { AnalysisResult } from '../types';

const resolveApiKey = (): string => {
  const key =
    (typeof import.meta !== 'undefined' && import.meta.env && (import.meta.env as Record<string, string | undefined>).VITE_GEMINI_API_KEY) ||
    (typeof process !== 'undefined' && process.env && (process.env.GEMINI_API_KEY || process.env.API_KEY)) ||
    '';

  if (!key) {
    throw new Error(
      'Gemini API anahtarı bulunamadı. Lütfen Netlify veya yerel ortamınızda GEMINI_API_KEY ya da VITE_GEMINI_API_KEY değişkenini ayarlayın.'
    );
  }

  return key;
};

let client: GoogleGenAI | null = null;

const getClient = () => {
  if (!client) {
    client = new GoogleGenAI({ apiKey: resolveApiKey() });
  }

  return client;
};

const analysisSchema = {
  type: Type.OBJECT,
  properties: {
    probability: {
      type: Type.NUMBER,
      description: "A number between 0 and 100 representing the percentage probability of the content being AI-generated.",
    },
    confidence: {
      type: Type.NUMBER,
      description: "A number between 0 and 10 representing the confidence interval range (e.g., a value of 5 means ±5%).",
    },
    summary: {
      type: Type.STRING,
      description: "A short, one-sentence summary of your findings. For example, 'The content appears to be AI-generated.' or 'The content appears to be written by a human.'",
    },
    breakdown: {
      type: Type.OBJECT,
      properties: {
        aiGenerated: { type: Type.NUMBER, description: "Percentage of content that seems AI generated." },
        mixed: { type: Type.NUMBER, description: "Percentage of content that seems mixed." },
        human: { type: Type.NUMBER, description: "Percentage of content that seems human-written." },
      },
      required: ["aiGenerated", "mixed", "human"],
    },
    reasoning: {
        type: Type.ARRAY,
        description: "Provide 3-4 key reasons for your conclusion. These should be technical or stylistic factors.",
        items: {
            type: Type.OBJECT,
            properties: {
                factor: { type: Type.STRING, description: "The name of the factor, e.g., 'Sentence Length Variance', 'Lexical Diversity', 'Lighting Inconsistencies', 'Unnatural Textures'." },
                score: { type: Type.NUMBER, description: "A score from 0 to 100 indicating how strongly this factor suggests AI generation." },
                explanation: { type: Type.STRING, description: "A brief, one-sentence explanation of this factor's impact." }
            },
            required: ["factor", "score", "explanation"]
        }
    },
    marginOfErrorWarning: {
      type: Type.STRING,
      description: "If the text type is 'Academic', 'Poetry', or 'Technical', provide a brief warning about the higher risk of false positives. Otherwise, this should be null."
    },
    model_version: {
      type: Type.STRING,
      description: "The version of the model used for this analysis. Always return 'Gemini 2.5 Pro'."
    }
  },
  required: ["probability", "summary", "breakdown", "confidence", "reasoning", "marginOfErrorWarning", "model_version"],
};

const languageMap: { [key: string]: string } = {
    en: 'English',
    tr: 'Turkish',
    ru: 'Russian',
    de: 'German'
};

export const analyzeText = async (text: string, textType: string, lang: string): Promise<AnalysisResult> => {
  const languageName = languageMap[lang] || 'English';
  const response = await getClient().models.generateContent({
    model: "gemini-2.5-pro",
    contents: {
      parts: [{ text: `Analyze the following text (categorized as ${textType}): "${text}"` }],
    },
    config: {
      systemInstruction: `You are an expert AI content detector. Your task is to analyze content, determine its AI generation likelihood, and provide a detailed breakdown of your reasoning. You must respond in the specified JSON format. ALL TEXT in your JSON response, including summaries and reasoning factors, MUST BE IN ${languageName}.`,
      responseMimeType: "application/json",
      responseSchema: analysisSchema,
    },
  });

  const jsonString = response.text;
  return JSON.parse(jsonString) as AnalysisResult;
};

export const analyzeImage = async (base64Image: string, mimeType: string, lang: string): Promise<Omit<AnalysisResult, 'marginOfErrorWarning'>> => {
    const languageName = languageMap[lang] || 'English';
    const imagePart = {
        inlineData: {
            data: base64Image,
            mimeType: mimeType,
        },
    };
    const textPart = {
        text: "Analyze the provided image to determine the likelihood that the image itself was generated by an AI. Base your analysis on visual cues like lighting, textures, object consistency, and any tell-tale artifacts common in AI-generated images. Do not perform OCR or analyze text within the image. Respond in the requested JSON format."
    };

    const response = await getClient().models.generateContent({
        model: "gemini-2.5-pro",
        contents: { parts: [imagePart, textPart] },
        config: {
            systemInstruction: `You are an expert in detecting AI-generated images. Your task is to analyze the visual properties of an image to determine its origin. Provide a probability score and detailed reasoning based on factors like 'Lighting and Shadows', 'Texture Realism', 'Object Consistency', and 'Background Details'. ALL TEXT in your JSON response, including summaries and reasoning factors, MUST BE IN ${languageName}. The marginOfErrorWarning should be null.`,
            responseMimeType: "application/json",
            responseSchema: analysisSchema,
        },
    });

    const jsonString = response.text;
    return JSON.parse(jsonString) as AnalysisResult;
};


export const humanizeText = async (text: string, tone: string): Promise<string> => {
  if (!text) return "";
  
  const prompt = `Rewrite the following text to make it sound as if it were written by a human, making it undetectable by AI detection tools. Apply a "${tone}" tone. IMPORTANT: Preserve the core meaning, and do not alter specific data like numbers, statistics, URLs, or proper nouns. Just provide the rewritten text without any extra commentary. Original text: "${text}"`;

  const response = await getClient().models.generateContent({
    model: "gem-2.5-pro",
    contents: prompt,
    config: {
      systemInstruction: "You are an expert writer who specializes in rewriting AI-generated text to make it sound completely human and pass AI detection tests, with a strong focus on meaning preservation."
    }
  });

  return response.text;
};

export const enhanceImageRealism = async (base64Image: string, mimeType: string): Promise<string> => {
    const imagePart = {
        inlineData: {
            data: base64Image,
            mimeType: mimeType,
        },
    };
    const textPart = {
        text: "Make this image more photorealistic. Enhance the lighting, textures, and details to make it look like a real photograph. The output should be only the enhanced image."
    };

    const response = await getClient().models.generateContent({
        model: "gemini-2.5-flash-image",
        contents: { parts: [imagePart, textPart] },
        config: {
            responseModalities: [Modality.IMAGE],
        },
    });

    for (const part of response.candidates[0].content.parts) {
        if (part.inlineData) {
            return part.inlineData.data;
        }
    }

    throw new Error("Image enhancement failed to produce an image.");
};